### ISSUE TITLE
v1.0 Checklist

### ISSUE THREAD

**Issue by faultyserver** [audiobahn404/test_cs352#3]
These are the features planned for v1.0, and their implementation status:
- [x] Complex file structure support. (d708ad329e) 
- [x] Case tagging for faster development (b8eb8104f).
- [ ] Assertion support for compiler validation.
- [x] Better support for windows.
- [ ] List of failed cases at the end of the output.

These changes will be checked off as they are implemented in the Ruby version of the script. There will be a separate issue linked to this one detailing the status of the Python port **after** these changes have been implemented and finalized.

**Comment by audiobahn404** [comment]
### Generic `.sh` and `.bat` Script Managers
As of v0.9, you choose to run the Python or the Ruby version of the test script by running either `ruby test.rb` or `python test.py`. While this works, it can be nicer.

This task aims to make a single file - `test.sh` Unix, `test.bat` for Windows - that can manage running different versions of the script for you. In addition, this allows us to move configuration defaults to a central location, which simplifies things both for us and for the user.

#### Examples (Unix)
Run the test script using all default values:
```bash
$ ./test
```

Run the test script, explicitly using the Python version:
```bash
$ ./test --lang python    # Or
$ ./test --python         # Or
$ ./test -P
```

Run the script on a different target program:
```bash
$ ./test --tester ./different_target    # Or
$ ./test -t ./different_target
```

Run the script with a different set of test cases:
```bash
$ ./test --cases ./test/other_tests
```

Run the script with multiple configuration options:
```bash
$ ./test --python --tester ./target --cases ./my_cases
```

#### Examples (Windows)
Run the test script using all default values:
```batch
> test
```

Run the test script, explicitly using the Python version:
```batch
> test /l python    # Or
> test /P
```

Run the script on a different target program:
```batch
> test /t ./different_target    # Or
```

Run the script with a different set of test cases:
```batch
> test /c ./test/other_tests
```

Run the script with multiple configuration options:
```batch
> test /P /t ./target /c ./my_cases
```

**Comment by faultyserver** [comment]
Assertion support is semi-complete, in the sense that we are able to test the output of a program. However, assertions imply a boolean comparison, which is not yet supported by miniscript.

Once that is added, we will be able to add proper assertion support.

**Comment by faultyserver** [comment]
Windows is supported about as well as it can be. ANSI codes don't affect the actual script, just the output. It'll still give the correct results, it just might not look as good as it can. Marking as complete for v1.0.
